version: '3'
services:
  couchbase:
    container_name: app-provision-couchbase
    image: couchbase-nosetup:community-7.1.1
    build:
      dockerfile: couchbase.Dockerfile
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    networks:
      - couchbase

networks:
  couchbase: