version: '3'
services:
  couchbase:
    container_name: app-provision-couchbase
    image: arm64v8/couchbase:community-7.7.1
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    networks:
      - couchbase

networks:
  couchbase: