@startuml
'https://plantuml.com/class-diagram

interface Configurations #orange {
    Flux<Configuration> findAllByType(String type)
    Mono<Configuration> getById(ExperimentId)
    Mono<Configuration> add(Configuration configuration)
    Mono<Configuration> update(ConfigurationId id, Configuration configuration)
    Mono<Configuration> delete(ConfigurationId id)
    Mono<Configuration> publish(ConfigurationId id)
    Mono<Configuration> disable(ConfigurationId id)
    Mono<Configuration> delete(ConfigurationId id)
}



class Configuration #pink {
    ConfigurationId id
    String type
    ConfigurationDescription description
}

class Customer #pink {
    CustomerId id
    String adCode
    CustomerLevel customerLevel
}



class CustomerCriteriaCondition {
    List<LocationCondition> locationConditions
    List<String> whiteList
}

class ConfigurationDescription {
    String title
    String description
    String key
    T data
    T trackingData
    StaticStatus staticStatus
    TimeRange timeRange
    DisplayRule displayRule
    DateTime createdAt
    DateTime updatedAt
    long priority

    DynamicStatus getStatus()
}

class DisplayRule {
    DisplayRuleType type
    int times
    List<DailyCondition> dailyConditions
}

enum DisplayRuleType {
    EVERYTIME
    FIX_TIMES
    DAY_FIX_TIMES
}

class DailyCondition {
    int dayOfWeek
    Time startTime
    Time endTime
}

class TimeRange {
    DateTime startDate
    DateTime endDate
}

enum StaticStatus {
    DRAFT
    PUBLISHED
    DISABLED
    DELETED
}

enum DynamicStatus {
    DRAFT
    NOT_BEGIN
    IN_PROGRESS
    EXPIRED
    DISABLED
    DELETED
}

interface CustomerCriteriaResult #orange{
    Mono<Boolean> getResult()
}

interface CustomerConfigurations #orange{
    FLux<Configuration> flux()
}

Customer  "1" -R- "1" CustomerConfigurations
CustomerConfigurations "1" -- "*" Configuration

Customer  "1" -- "1" CustomerCriteriaResult
CustomerCriteriaCondition  "1" -L- "1" CustomerCriteriaResult



Configurations "*" -- "1" Configuration
Configuration *- ConfigurationDescription
Configuration "1" -- "1" CustomerCriteriaCondition

ConfigurationDescription *- StaticStatus
ConfigurationDescription o- DynamicStatus
ConfigurationDescription *- TimeRange
ConfigurationDescription *- DisplayRule
DisplayRule *- DisplayRuleType
DisplayRule *- DailyCondition


interface ConfigurationDiffer #orange{
   Mono<DifferResult<T>> diff(String type, String version, Customer customer)
}


class DifferResult #pink{
    String type
    boolean hasUpdate
    boolean useDefault
    List<T> content
    String version
    DateTime expireTime
}

class DifferItem #pink{
    String id
    String key
    T Data
    T trackingData
    DisplayRule displayRule
    DateTime updatedAt
    long priority
}

class IncrementalDifferItem extends DifferItem{
    boolean deleted
}

class FullDiffer implements ConfigurationDiffer {
    Mono<DifferResult<DifferItem>> diff(String type, String version, Customer customer)
}

class IncrementalDiffer implements ConfigurationDiffer {
    Mono<DifferResult<IncrementalDifferItem>> diff(String type, String version, Customer customer)
}

 DifferResult -D-o ConfigurationDiffer

ConfigurationDiffer o-D- CustomerConfigurations

FullDiffer o- DifferItem

IncrementalDiffer o- IncrementalDifferItem

@enduml
