server:
  port: 8088

spring:
  main:
    lazy-initialization: false
  data:
    couchbase:
      repositories:
        type: auto
      auto-index: true
      bucket-name: bucket1

  couchbase:
    connection-string: couchbase://127.0.0.1
    username: bucket1
    password: bucket1pass
  rsocket:
    server:
      port: 7001
      transport: tcp

logging:
  level:
    root: debug
    org.springframework.data.couchbase: trace